_target_: yolo11n-fusion.yaml # Inherit from our new fusion yaml

# Add ECA to the backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]                            # 0
  - [-1, 1, Conv, [128, 3, 2]]                           # 1
  - [-1, 2, C3k2, [256, False, 0.25]]                    # 2
  - [-1, 1, Conv, [256, 3, 2]]                           # 3
  - [-1, 2, C3k2, [512, False, 0.25]]                    # 4
  - [-1, 1, modules.custom_modules.ECA, [512]]           # <-- Injected ECA
  - [-1, 1, Conv, [512, 3, 2]]                           # 6
  - [-1, 2, C3k2, [512, True]]                           # 7
  - [-1, 1, modules.custom_modules.ECA, [512]]           # <-- Injected ECA
  - [-1, 1, Conv, [1024, 3, 2]]                          # 9
  - [-1, 2, C3k2, [1024, True]]                          # 10
  - [-1, 1, modules.custom_modules.ECA, [1024]]          # <-- Injected ECA
  - [-1, 1, SPPF, [1024, 5]]                             # 12
  - [-1, 2, C2PSA, [1024]]                               # 13