_target_: yolo11n-csab-fusion.yaml # Inherit from the CSAB+Fusion yaml

# Now, add ECA modules to the already modified backbone
backbone:
  - [-1, 1, Conv, [64, 3, 2]]                            # 0
  - [-1, 1, Conv, [128, 3, 2]]                           # 1
  - [-1, 2, C3k2, [256, False, 0.25]]                    # 2
  - [-1, 1, Conv, [256, 3, 2]]                           # 3
  - [-1, 2, C3k2, [512, False, 0.25]]                    # 4
  - [-1, 1, modules.custom_modules.ECA, [512]]           # <-- Injected ECA
  - [-1, 1, Conv, [512, 3, 2]]                           # 6
  - [-1, 1, modules.custom_modules.CSAB_Offset, [512]]   # 7 <-- Replaced C3k2
  - [-1, 1, modules.custom_modules.ECA, [512]]           # <-- Injected ECA
  - [-1, 1, Conv, [1024, 3, 2]]                          # 9
  - [-1, 1, modules.custom_modules.CSAB_Offset, [1024]]  # 10 <-- Replaced C3k2
  - [-1, 1, modules.custom_modules.ECA, [1024]]          # <-- Injected ECA
  - [-1, 1, SPPF, [1024, 5]]                             # 12
  - [-1, 2, C2PSA, [1024]]                               # 13