_target_: yolo11n-fusion.yaml # Inherit from our new fusion yaml

# Add CSAB_Offset to the backbone (replacing key C3k2 blocks)
backbone:
  - [-1, 1, Conv, [64, 3, 2]]                            # 0
  - [-1, 1, Conv, [128, 3, 2]]                           # 1
  - [-1, 2, C3k2, [256, False, 0.25]]                    # 2
  - [-1, 1, Conv, [256, 3, 2]]                           # 3
  - [-1, 2, C3k2, [512, False, 0.25]]                    # 4
  - [-1, 1, Conv, [512, 3, 2]]                           # 5
  - [-1, 1, modules.custom_modules.CSAB_Offset, [512]]   # 6 <-- Replaced C3k2
  - [-1, 1, Conv, [1024, 3, 2]]                          # 7
  - [-1, 1, modules.custom_modules.CSAB_Offset, [1024]]  # 8 <-- Replaced C3k2
  - [-1, 1, SPPF, [1024, 5]]                             # 9
  - [-1, 2, C2PSA, [1024]]                               # 10